#pragma once

typedef enum _LW_BATTLE_STATE {
	// Player turn
	LBS_SELECT_COMMAND,
	LBS_SELECT_TARGET,
	LBS_COMMAND_IN_PROGRESS,
	// Enemy turn
	LBS_START_ENEMY_TURN,
	LBS_ENEMY_TURN_WAIT,
	LBS_ENEMY_COMMAND_IN_PROGRESS,
} LW_BATTLE_STATE;
