#pragma once
#include "linmath.h"

typedef enum _LW_SPHERE_BATTLE_PACKET_TYPE {
	LSBPT_GETTOKEN,
	LSBPT_TOKEN,
	LSBPT_QUEUE,
	LSBPT_MATCHED,
	LSBPT_PLAYER_DAMAGED,
	// tcp
	LSBPT_LWSPHEREBATTLEPACKETQUEUE2 = 200,
	LSBPT_LWSPHEREBATTLEPACKETMAYBEMATCHED = 201,
	LSBPT_LWSPHEREBATTLEPACKETMATCHED2 = 202,
	LSBPT_LWSPHEREBATTLEPACKETQUEUEOK = 203,
	LSBPT_LWSPHEREBATTLEPACKETRETRYQUEUE = 204,
} LW_SPHERE_BATTLE_PACKET_TYPE;

// Client -> Server
typedef struct _LWSPHEREBATTLEPACKETGETTOKEN {
	int type;
} LWSPHEREBATTLEPACKETGETTOKEN;

// Server --> Client
typedef struct _LWSPHEREBATTLEPACKETTOKEN {
	int type;
	int token;
} LWSPHEREBATTLEPACKETTOKEN;

// Client --> Server
typedef struct _LWSPHEREBATTLEPACKETQUEUE {
	int type;
	int token;
} LWSPHEREBATTLEPACKETQUEUE;

// Server --> Client
typedef struct _LWSPHEREBATTLEPACKETMATCHED {
	int type;
	int master;
} LWSPHEREBATTLEPACKETMATCHED;

typedef struct _LWSPHEREBATTLEPACKETPLAYERDAMAGED {
	int type;
} LWSPHEREBATTLEPACKETPLAYERDAMAGED;

#pragma pack(push, 1)
typedef struct _LWSPHEREBATTLEPACKETQUEUE2 {
	unsigned short size;
	unsigned short type;
} LWSPHEREBATTLEPACKETQUEUE2;

typedef struct _LWSPHEREBATTLEPACKETQUEUEOK {
	unsigned short size;
	unsigned short type;
} LWSPHEREBATTLEPACKETQUEUEOK;

typedef struct _LWSPHEREBATTLEPACKETRETRYQUEUE {
	unsigned short size;
	unsigned short type;
} LWSPHEREBATTLEPACKETRETRYQUEUE;

typedef struct _LWSPHEREBATTLEPACKETMAYBEMATCHED {
	unsigned short size;
	unsigned short type;
} LWSPHEREBATTLEPACKETMAYBEMATCHED;

typedef struct _LWSPHEREBATTLEPACKETMATCHED2 {
	unsigned short size;
	unsigned short type;
	unsigned char ipaddr[4];
	unsigned short port;
} LWSPHEREBATTLEPACKETMATCHED2;
#pragma pack(pop)
